// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// onewire_reset //
// ------------- //

#define onewire_reset_wrap_target 0
#define onewire_reset_wrap 7
#define onewire_reset_pio_version 1

static const uint16_t onewire_reset_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0
    0xe081, //  1: set    pindirs, 1
    0x80a0, //  2: pull   block
    0xa027, //  3: mov    x, osr
    0x0044, //  4: jmp    x--, 4
    0xe080, //  5: set    pindirs, 0
    0x3f20, //  6: wait   0 pin, 0               [31]
    0x3fa0, //  7: wait   1 pin, 0               [31]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program onewire_reset_program = {
    .instructions = onewire_reset_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = onewire_reset_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config onewire_reset_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + onewire_reset_wrap_target, offset + onewire_reset_wrap);
    return c;
}
#endif

