// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// onewire_read //
// ------------ //

#define onewire_read_wrap_target 0
#define onewire_read_wrap 9
#define onewire_read_pio_version 1

static const uint16_t onewire_read_program_instructions[] = {
            //     .wrap_target
    0xe047, //  0: set    y, 7
    0xe000, //  1: set    pins, 0
    0xe281, //  2: set    pindirs, 1             [2]
    0xe080, //  3: set    pindirs, 0
    0xa542, //  4: nop                           [5]
    0x4001, //  5: in     pins, 1
    0xbf42, //  6: nop                           [31]
    0xaf42, //  7: nop                           [15]
    0x0081, //  8: jmp    y--, 1
    0x8020, //  9: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program onewire_read_program = {
    .instructions = onewire_read_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = onewire_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config onewire_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + onewire_read_wrap_target, offset + onewire_read_wrap);
    return c;
}
#endif

